server:
  port: ${SERVER_PORT:2333}

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:vinaymusic}

    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      rotation: true
      distortion: true
      channelMix: true
      lowPass: true

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5"
      repository: "https://maven.lavalink.dev/releases"

    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.0-beta.5"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    clients:
      - MUSIC
      - WEB

  lavasrc:
    providers:
      - "ytsearch:%QUERY%"
      - "ytmsearch:%QUERY%"

    sources:
      spotify: true
      applemusic: true
      deezer: true
      yandexmusic: false
      flowerytts: false

logging:
  level:
    root: INFO
    lavalink: INFO
